theme: minima
markdown: kramdown

title: Learning Multi-finger Grasping of Unknown Objects
author: "{dominik.winkelbauer,berthold.baeuml,rudolph.triebel}@dlr.de"

header_pages:
  - index.md
  - _pages/iros23.md
  - _pages/humanoids23.md

include:
    - _pages

exclude:
    - .gitignore
    - Gemfile
    - README.md
